"""init

Revision ID: 632a043a3e9f
Revises: 2030ecc7d696
Create Date: 2020-02-26 10:11:32.727288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632a043a3e9f'
down_revision = '2030ecc7d696'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
